import Foundation
import AppKit

class PythonBridge {
    private let pythonScriptsPath: URL
    
    init() {
        // Get the path to Python scripts directory
        // Use current working directory or home directory for scripts
        let homeDir = FileManager.default.homeDirectoryForCurrentUser
        let scriptsPath = homeDir
            .appendingPathComponent(".pioneer")
            .appendingPathComponent("PythonScripts")
        
        // Create scripts directory if it doesn't exist
        try? FileManager.default.createDirectory(at: scriptsPath, withIntermediateDirectories: true)
        
        self.pythonScriptsPath = scriptsPath
        
        // Initialize Python scripts
        initializePythonScripts()
    }
    
    private func initializePythonScripts() {
        // Create main Python script for code generation
        let mainScript = """
        #!/usr/bin/env python3
        import json
        import sys
        import os
        from pathlib import Path

        def generate_iphone_app(node_data):
            \"\"\"Generate an iPhone app from node data\"\"\"
            node = json.loads(node_data)
            app_name = node.get('name', 'GeneratedApp')
            code = node.get('code', '')
            
            output_dir = Path(f"generated/{app_name}")
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # Create SwiftUI app structure
            app_file = output_dir / f"{app_name}App.swift"
            content_file = output_dir / "ContentView.swift"
            
            with open(app_file, 'w') as f:
                f.write(f\"\"\"
        import SwiftUI

        @main
        struct {app_name}App: App {{
            var body: some Scene {{
                WindowGroup {{
                    ContentView()
                }}
            }}
        }}
        \"\"\")
            
            with open(content_file, 'w') as f:
                if code:
                    f.write(code)
                else:
                    f.write(f\"\"\"
        import SwiftUI

        struct ContentView: View {{
            var body: some View {{
                VStack {{
                    Text("Hello, {app_name}!")
                        .font(.largeTitle)
                }}
                .padding()
            }}
        }}
        \"\"\")
            
            print(f"Generated iPhone app: {output_dir.absolute()}")
            return str(output_dir.absolute())

        def generate_website(node_data):
            \"\"\"Generate a website from node data\"\"\"
            node = json.loads(node_data)
            site_name = node.get('name', 'GeneratedSite')
            code = node.get('code', '')
            
            output_dir = Path(f"generated/{site_name}")
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # Create HTML structure
            index_file = output_dir / "index.html"
            css_file = output_dir / "style.css"
            js_file = output_dir / "script.js"
            
            with open(index_file, 'w') as f:
                if code:
                    f.write(code)
                else:
                    f.write(f\"\"\"
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>{site_name}</title>
            <link rel="stylesheet" href="style.css">
        </head>
        <body>
            <div class="container">
                <h1>Welcome to {site_name}</h1>
                <p>Generated by Pioneer</p>
            </div>
            <script src="script.js"></script>
        </body>
        </html>
        \"\"\")
            
            with open(css_file, 'w') as f:
                f.write(\"\"\"
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }
        \"\"\")
            
            with open(js_file, 'w') as f:
                f.write("// JavaScript for " + site_name + "\\n")
            
            print(f"Generated website: {output_dir.absolute()}")
            return str(output_dir.absolute())

        def deploy_to_aws(node_data):
            \"\"\"Deploy backend to AWS\"\"\"
            node = json.loads(node_data)
            backend_name = node.get('name', 'GeneratedBackend')
            
            # This is a stub - would integrate with AWS SDK
            print(f"Deploying {backend_name} to AWS...")
            print("(This is a placeholder - implement AWS deployment logic)")
            
            # Would typically:
            # 1. Create CloudFormation template
            # 2. Deploy Lambda functions
            # 3. Set up API Gateway
            # 4. Configure IAM roles
            # etc.
            
            return f"AWS deployment initiated for {backend_name}"

        if __name__ == "__main__":
            if len(sys.argv) < 3:
                print("Usage: python3 script.py <action> <node_json>")
                sys.exit(1)
            
            action = sys.argv[1]
            node_data = sys.argv[2]
            
            if action == "generate_iphone_app":
                result = generate_iphone_app(node_data)
            elif action == "generate_website":
                result = generate_website(node_data)
            elif action == "deploy_to_aws":
                result = deploy_to_aws(node_data)
            else:
                print(f"Unknown action: {action}")
                sys.exit(1)
            
            print(result)
        """
        
        let scriptURL = pythonScriptsPath.appendingPathComponent("generator.py")
        try? mainScript.write(to: scriptURL, atomically: true, encoding: .utf8)
        
        // Make script executable
        let process = Process()
        process.launchPath = "/bin/chmod"
        process.arguments = ["+x", scriptURL.path]
        try? process.run()
        process.waitUntilExit()
    }
    
    func generateiPhoneApp(node: Node) async {
        await runPythonScript(action: "generate_iphone_app", node: node)
    }
    
    func generateWebsite(node: Node) async {
        await runPythonScript(action: "generate_website", node: node)
    }
    
    func deployToAWS(node: Node) async {
        await runPythonScript(action: "deploy_to_aws", node: node)
    }
    
    private func runPythonScript(action: String, node: Node) async {
        let scriptURL = pythonScriptsPath.appendingPathComponent("generator.py")
        
        // Convert node to JSON
        let encoder = JSONEncoder()
        guard let nodeData = try? encoder.encode(node),
              let nodeJSON = String(data: nodeData, encoding: .utf8) else {
            print("Failed to encode node to JSON")
            return
        }
        
        // Run Python script
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        process.arguments = [scriptURL.path, action, nodeJSON]
        
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        
        do {
            try process.run()
            process.waitUntilExit()
            
            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            if let output = String(data: data, encoding: .utf8) {
                print("Python output: \(output)")
                
                // Show alert to user
                await MainActor.run {
                    showAlert(title: "Generation Complete", message: output)
                }
            }
        } catch {
            print("Error running Python script: \(error)")
            await MainActor.run {
                showAlert(title: "Error", message: "Failed to run generation script: \(error.localizedDescription)")
            }
        }
    }
    
    private func showAlert(title: String, message: String) {
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = message
        alert.alertStyle = .informational
        alert.addButton(withTitle: "OK")
        alert.runModal()
    }
}

